name: Publish to Live

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  rebase:
    runs-on: ubuntu-latest

    steps:
      - name: Generate token from GitHub App
        id: generate-token
        uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf #2.2.1
        with:
          app-id: ${{ secrets.SEQUESTER_APPID }}
          private-key: ${{ secrets.SEQUESTER_PRIVATEKEY }}

      - name: Checkout repository
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 #@v4.2.1
        with:
          fetch-depth: 0
          token: ${{ steps.generate-token.outputs.token }}

      - name: Rebase live with main
        run: |
          git fetch origin main:main
          git fetch origin live:live
          git checkout live
          git rebase main

      - name: Push changes
        run: |
          git push origin live
